name: docker

on: pull_request

jobs:
  build-codeowners:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build the codeowners container image
      run: docker build -f Dockerfile.codeowners -t timbot:codeowners .

  build-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Start the default mysql service
      run: sudo systemctl start mysql.service
    - name: Add the test schema.sql
      run: |
        set -ex
        tail -n +2 ./schema.sql > schema.tmp.sql
        mysql -uroot -proot < ./schema.tmp.sql
    - name: Ensure the MySQL container is healthy
      run: mysql -uroot -proot -e "select * from timbot.users;"
    - name: Build the timbot container image
      run: docker build -f Dockerfile -t timbot:timbot .
