name: quay

on: pull_request

# on:
#   push:
#     branches:
#       - master

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: "{\"commit\":\"${GITHUB_SHA}\",\"ref\":\"${GITHUB_REF}\",\"default_branch\":\"master\"}"
      URL: ${{ secrets.QUAY_WEBHOOK_URL }}
    steps:
    - name: update container on quay.io
      run: |
        curl -H "Content-Type:application/json" "$URL"
        # -d '${PAYLOAD}'
