name: quay

on: push

# on:
#   push:
#     branches:
#       - master

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      header: "Content-Type:application/json"
      payload: "{\"commit\":\"${{ github.sha }}\",\"ref\":\"${{ github.ref }}\",\"default_branch\":\"master\"}"
      url: "${{ secrets.QUAY_WEBHOOK_URL }}"
    steps:
    - name: debug
      run: |
        echo $header
        echo $payload
    - name: update container on quay.io
      run: curl -H $header -d $payload $url
